In [1]:
import numpy as np

## Creating Numpy Array

In [2]:
type(np.array(["abc", 2, 3]))

numpy.ndarray

In [3]:
np.array([1, 2, 5], ndmin=5)

array([[[[[1, 2, 5]]]]])

In [4]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [5]:
np.asarray((1,2))

array([1, 2])

In [8]:
np.asanyarray([2,4])

array([2, 4])

## Numpy from functions

In [9]:
# return an array using applied function ,ex: lambda 
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)


array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [10]:
#return an array using iterable
iterable = (x*x for x in range(5))
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [11]:
#convert the string element to array element
np.fromstring('15 2 43 4', dtype=int, sep=' ')


array([15,  2, 43,  4])

In [12]:
#for an array by making indexwise combination of elements
x1= np.array([1,2,3])
x2= np.array(['abc','xyz','sed'])
x3= np.array([2.5, 5.6, 8.90])
np.core.records.fromarrays([x1,x2,x3])

rec.array([(1, 'abc', 2.5), (2, 'xyz', 5.6), (3, 'sed', 8.9)],
          dtype=[('f0', '<i4'), ('f1', '<U3'), ('f2', '<f8')])

## arange, linspace and logspace

In [13]:
np.arange(5,16,2.3)    

array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [14]:
np.linspace(1,5,10)  

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [15]:
np.logspace(2,3,4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

## Matrix Creation

In [17]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
print(np.empty((3,6)))

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.29061074e-306
  1.89146896e-307 1.37961302e-306]
 [1.05699242e-307 8.01097889e-307 1.78020169e-306 7.56601165e-307
  1.02359984e-306 1.33510679e-306]
 [2.22522597e-306 8.01097889e-307 1.60220800e-306 7.56601165e-307
  2.22522596e-306 1.42404727e-306]]


In [26]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Random Number Generation

In [27]:
np.random.rand(2,3)

array([[0.46003499, 0.50533395, 0.55212454],
       [0.75449419, 0.10274093, 0.56914225]])

In [28]:
np.random.randn(4,3)

array([[-0.98544564,  1.00478602,  0.11058838],
       [-0.85825348, -1.99882222, -0.8282433 ],
       [-1.06360275,  0.9440754 , -0.75745408],
       [-0.53121606, -1.10324209,  0.62472263]])

In [29]:
np.random.randint(10,size=(3,4))

array([[6, 8, 4, 6],
       [1, 0, 8, 8],
       [8, 8, 2, 7]])

## Reshaping and Sorting

In [33]:
arr=np.random.randint(10,size=(4,3))
arr

array([[0, 8, 5],
       [9, 2, 4],
       [1, 6, 0],
       [5, 5, 9]])

In [34]:
arr.reshape((6,2))

array([[0, 8],
       [5, 9],
       [2, 4],
       [1, 6],
       [0, 5],
       [5, 9]])

In [35]:
#passing negative value as second parameter
arr.reshape((3,-34564))

array([[0, 8, 5, 9],
       [2, 4, 1, 6],
       [0, 5, 5, 9]])

In [36]:
np.sort(arr)

array([[0, 5, 8],
       [2, 4, 9],
       [0, 1, 6],
       [5, 5, 9]])

In [39]:
#will sort on first axis by applying merge sort 
np.sort(arr,axis=0,kind='mergesort')

array([[0, 2, 0],
       [1, 5, 4],
       [5, 6, 5],
       [9, 8, 9]])

## Slicing and Indexing

In [43]:
arr=np.random.randint(10,size=(4,3))
arr


array([[7, 8, 9],
       [9, 5, 8],
       [6, 4, 8],
       [6, 7, 2]])

In [49]:
#rows from 0 to 2 excluding 3 with step size 1
arr[0:3:1]

array([[7, 8, 9],
       [9, 5, 8],
       [6, 4, 8]])

In [50]:
#from cloumn at index 2, gives data at index 0 to 1 excluding 2
arr[0:2,2]

array([9, 8])

## Universal Functions

#### Trigonometric Functions

In [56]:
arr=[0,1,2]
np.sin(arr)

array([ 0.        ,  0.84147098, -0.8462204 ])

In [58]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.53283302])

#### Statistical Functional

In [59]:
weight = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45])
np.amin(weight)

45.0

In [60]:
np.amax(weight)

73.25

In [61]:
np.average(weight)

54.3225

#### Mathematical Function

In [62]:
x=[1,2]
y=[3,4]
np.add(x,y)

array([4, 6])

In [64]:
np.subtract(x,y)

array([-2, -2])

In [65]:
np.power(x,y)

array([ 1, 16], dtype=int32)

#### Bit-twiddling functions

In [66]:
even = np.array([0, 2, 4, 6, 8, 16, 32])
odd = np.array([1, 3, 5, 7, 9, 17, 33])
np.bitwise_and(even, odd)

array([ 0,  2,  4,  6,  8, 16, 32], dtype=int32)

#### Matrix Multiplication

In [70]:
from numpy.random import randint as rdt
x = np.array(rdt(1,10,9)).reshape(3,3)
y = np.array(rdt(1,10,9)).reshape(3,3)

#Values multiplication based on index
x*y

array([[20, 45, 18],
       [ 6, 18, 21],
       [49, 56, 32]])

In [72]:
# Normal matrix multiplication
x@y

array([[ 61,  66, 116],
       [ 47,  49,  72],
       [108, 115, 151]])